### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\node_modules\s3-etag\index.js require() of ES modules is not supported.

### ISSUE THREAD

**Issue by leopucci** [badsyntax/s3-etag#32]
Can´t use this module using `const generateETag = require('s3-etag'); `
can´t use import on this code that I am working on.

**Comment by badsyntax** [comment]
Ahh, sorry about that. Thanks for letting me know. I will ship a hybrid package to support esm & commonjs. Will try get to that this week, just a bit busy at the mo.

**Comment by leopucci** [comment]
Hey Richard your package is by far the best one, I am sorry I could not create a PR for you because of my lack of knowledge. Just found your blog post about it. 
Nice work

**Comment by badsyntax** [comment]
I've publish a new version that exports both esm & commonjs. I'm not sure if I've done it correctly though. Can you install the latest version (1.0.2) and let me know if it fixes it for you?

**Comment by leopucci** [comment]
Yes give me a minute I get back to you

**Comment by leopucci** [comment]
![image](https://user-images.githubusercontent.com/38509299/153034513-7c968fec-1d42-48f0-a461-4774b2dab55a.png)

**Comment by badsyntax** [comment]
I published 1.0.3 to fix the warnings.

Are you able to import the package with require?

**Comment by leopucci** [comment]
It works if I declare this way 
`const generateETag = require('s3-etag').generateETag`
it is generating the etag properly

**Comment by badsyntax** [comment]
Cool. This should work: `const {generateETag} = require('s3-etag');` (it works for me)

**Comment by leopucci** [comment]
> Cool. This should work: `const {generateETag} = require('s3-etag');` (it works for me)

Indeed i will change it

**Comment by leopucci** [comment]
```
 "etag": "94a8ce3241a491c22c57a948bfcbc2cd-1"
 "etag": "d41d8cd98f00b204e9800998ecf8427e-0"
```

Working ok, thank you Richard!

**Comment by leopucci** [comment]
Richard, just a thing for the future to you think about it. 
When I hash files, i create a `fs.createReadStream(path) ` and do it on chunks, using  `.on('data', (data) => hash.update(data))`
the thing is that on('error') i can handle it properly. 
The most common error is while reading the file, the file gets deleted or changed. 
So this is a common thing to do, handle the ERROR_EBUSY when it happens

```
.on('error', (err) => {
        let endTime = new Date().getTime();
        const time = endTime - startTime;
        const seconds = time / 1000;
        if (err.message.indexOf('EBUSY') !== -1) {
          resolve({
            tipo: 'ERROR_EBUSY',
            timeSpent: seconds,
            path: path,
          });
        }
```

**Comment by badsyntax** [comment]
It's a good suggestion, I've added https://github.com/badsyntax/s3-etag/issues/39 to track this
